[common]
  interface = "eth0"
  pwd_hash  = "bfc6885fabb921c9c9094cb0118864a4605bec2cdf81869ee844ec2c7f1b7f73" # test
  log_path  = "acc-server.log"

[server]
  conn_pool_size   = 64
  num_frame_sender = 64
  timeout          = "15s"

[tcp]
  enabled = true
  network = "tcp"
  address = "0.0.0.0:2080"

[udp]
  enabled = true
  network = "udp"
  address = "0.0.0.0:2080"

[tls]
  server_cert = "certs/server_cert.pem"
  server_key  = "certs/server_key.pem"
  client_ca   = "certs/client_ca.pem"

[nat]
  enabled     = false
  map_timeout = "1m"

  [nat.mac]
    local   = "AB:FF:FF:FF:FF:FF"
    gateway = "AC:FF:FF:FF:FF:FF"

  [nat.ipv4]
    enabled = true
    local   = "192.168.1.2"
    gateway = "192.168.1.1"

  [nat.ipv6]
    enabled = false
    local   = "240c::2"
    gateway = "240c::1"